environment: development

server:
  host: "127.0.0.1"
  port: 3000
  request_timeout: 30
  graceful_shutdown_timeout: 30

database:
  max_connections: 100
  min_connections: 5
  max_lifetime: 1800
  idle_timeout: 300
  connect_timeout: 10

redis:
  pool_max_open: 100
  pool_max_idle: 10
  pool_timeout: 30
  pool_expire: 300

minio:
  region: "us-east-1"
  use_ssl: false

jwt:
  expiration: "24h"
  refresh_expiration: "7d"

telemetry:
  log_level: "debug"
